In [1]:
import torch
import torch.nn as nn
import numpy as np
import torchvision
from torchvision import transforms
from torchvision.datasets import ImageFolder
import matplotlib.pyplot as plt

### Calcular gradientes con pytorch
Se utiliza el paquete autograd de pytroch que simplifica mucho el proceso

In [19]:
print("supongamos que quieremos los gradientes de un tensor random")
x = torch.rand(3, requires_grad=True) #Recordar el requires_grad, si es False genera error
print(x)

print("Cada vez que hacemos operaciones en este tensor pytorch creara un grafo computacional para nosotros, por ejemplo")
y = x + 2

print("en sintesis, tenemos un nodo con entradas y salidas")
print("revisar https://youtu.be/c36lUUr864M?list=RDCMUCbXgNpp0jedKWcQiULLbDTA&t=1666")
print("sirve harto pal forward/backpropagation, concepto de ML")
print("si vemos la operaciones que hicimos se agrega el AddBackward")
print(y) #observe que se agrega el backward
print("Lo mismo con la multiplicaciones MultBackward")
z = y*y*2
print(z)
print("incluso la media")
z = z.mean()
print(z)
print("para calcular el o los gradiente basta con call la funcion backward")
z.backward() # dz/dx
print(x.grad) 
print("Recuerde que en el fondo estamos creando el Jacobiano y no solo 1 vetor gradiente")
print("revisar https://youtu.be/c36lUUr864M?list=RDCMUCbXgNpp0jedKWcQiULLbDTA&t=1898")
print("como este caso es escalar no hay que especifivar nada en z backward")

supongamos que quieremos los gradientes de un tensor random
tensor([0.9408, 0.2847, 0.5905], requires_grad=True)
Cada vez que hacemos operaciones en este tensor pytorch creara un grafo computacional para nosotros, por ejemplo
en sintesis, tenemos un nodo con entradas y salidas
revisar https://youtu.be/c36lUUr864M?list=RDCMUCbXgNpp0jedKWcQiULLbDTA&t=1666
sirve harto pal forward/backpropagation, concepto de ML
si vemos la operaciones que hicimos se agrega el AddBackward
tensor([2.9408, 2.2847, 2.5905], grad_fn=<AddBackward0>)
Lo mismo con la multiplicaciones MultBackward
tensor([17.2968, 10.4400, 13.4212], grad_fn=<MulBackward0>)
incluso la media
tensor(13.7193, grad_fn=<MeanBackward0>)
para calcular el o los gradiente basta con call la funcion backward
tensor([3.9211, 3.0463, 3.4540])
Recuerde que en el fondo estamos creando el Jacobiano y no solo 1 vetor gradiente
revisar https://youtu.be/c36lUUr864M?list=RDCMUCbXgNpp0jedKWcQiULLbDTA&t=1898
como este caso es escalar no hay que especifi

In [21]:
print("Mismo caso pero ahora z no es escalar (quitamos el mean), el backward generará error, ya que estamos calculando el JACOBIANO")
x = torch.rand(3, requires_grad=True) #Recordar el requires_grad, si es False genera error
print(x)

y = x + 2

print(y) #observe que se agrega el backward

z = y*y*2
print(z)
#z = z.mean()
#print(z)
z.backward() # dz/dx
print(x.grad) 


Mismo caso pero ahora z no es escalar (quitamos el mean), el backward generará error
tensor([0.3977, 0.5265, 0.8670], requires_grad=True)
tensor([2.3977, 2.5265, 2.8670], grad_fn=<AddBackward0>)
tensor([11.4977, 12.7669, 16.4398], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

In [28]:
print("En este caso tenemos que darle de argumento un vector del mismo tamaño")
x = torch.ones(3, requires_grad=True) #Recordar el requires_grad, si es False genera error
print("x = ",x)

y = x + 2

print("y = ",y) #observe que se agrega el backward

z = y*y*2
print("z = ",z)
#z = z.mean()
#print(z)
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32) #aqui le pase un vector con constantes distintas
#v = torch.tensor([1.0,1.0,1.0],dtype=torch.float32) #aqui le pase un vector con constantes IGUALES
z.backward(v) # dz/dx 
print("x_grad = ",x.grad) 


En este caso tenemos que darle de argumento un vector del mismo tamaño
x =  tensor([1., 1., 1.], requires_grad=True)
y =  tensor([3., 3., 3.], grad_fn=<AddBackward0>)
z =  tensor([18., 18., 18.], grad_fn=<MulBackward0>)
x_grad =  tensor([ 1.2000, 12.0000,  0.0120])


In [39]:
  print("prevenir el 'tracking' de gradiantes: https://youtu.be/c36lUUr864M?list=RDCMUCbXgNpp0jedKWcQiULLbDTA&t=2062")
x = torch.rand(3, requires_grad=True)
print(x)
#print("opcion 1 x.requires_grad_(False)")
#x.requires_grad_(False)
#print(x)
#print(x+9)
#print("opcion 2 x.detach(): crear un nuevo vector pero sin grad")
#x.detach()
#v = x.detach()
#print(v)
print("opcion 3 with torch.no_grad():")
with torch.no_grad():
    y = x + 2
    print(y)

print("Cada vez que hacemos backrpro entonces el gradientes de un tensor determinado se ira acumulanndo. Hay que tener cuidadp")


prevenir el 'tracking' de gradiantes: https://youtu.be/c36lUUr864M?list=RDCMUCbXgNpp0jedKWcQiULLbDTA&t=2062
tensor([0.2569, 0.5557, 0.0789], requires_grad=True)
opcion 3 with torch.no_grad():
tensor([2.2569, 2.5557, 2.0789])


In [44]:
print("ejemplito")

weights = torch.ones(4, requires_grad=True)
print(weights)
print("trining loop")

for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

print("Se acomulan los valores de grad!!, dando valores incorrectos!!")

print("con optimizacion")
weights = torch.ones(4, requires_grad=True)
print(weights)
print("trining loop")

for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

ejemplito
tensor([1., 1., 1., 1.], requires_grad=True)
trining loop
tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
Se acomulan los valores de grad!!, dando valores incorrectos!!
con optimizacion
tensor([1., 1., 1., 1.], requires_grad=True)
trining loop
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
