In [1]:
import torch
import torch.nn as nn
import numpy as np
import torchvision
from torchvision import transforms
from torchvision.datasets import ImageFolder
import matplotlib.pyplot as plt

In [2]:
# Crear tensores vacios y distintas dimensiones
x = torch.empty(1) # Tensor q solo es un valor escalar
y = torch.empty(3) # Tensor q es como una lista, 3 valores
z = torch.empty(2,3) # Tensor de dos dimensiones 2x3
zz = torch.empty(4,2,3) # Tensor de tres dimensiones 4x2x3
d = torch.empty(2,2,2,3) # Tensor de cuatro dimensiones 2x2x2x3
print("----escalar---")
print(x)
print("---lista 3 valores----")
print(y)
print("----Matrix 2x3----")
print(z)
print("----3d 4x2x3----")
print(zz)
print("---'4d'-2x2x2x3--")
print(d)


----escalar---
tensor([0.])
---lista 3 valores----
tensor([1.1729e-42, 0.0000e+00, 2.6218e+23])
----Matrix 2x3----
tensor([[9.1837e-39, 2.9389e-39, 1.0469e-38],
        [8.9082e-39, 2.9389e-39, 1.0102e-38]])
----3d 4x2x3----
tensor([[[ 8.8674e-04,  1.7181e+19,  4.3059e+21],
         [ 6.5831e+19,  7.2708e+31,  1.0999e-32]],

        [[ 1.3563e-19,  5.1848e-43,  6.1267e+20],
         [ 4.2328e+21,  7.0065e-45,  0.0000e+00]],

        [[ 2.1019e-44,  1.2612e-44,  9.3887e-44],
         [ 1.1065e-40,  3.8823e+25,  2.6685e+36]],

        [[ 2.3971e-38,  2.7516e+36,  9.6197e+21],
         [ 9.2583e+18,  3.9134e+25, -3.7734e-37]]])
---'4d'-2x2x2x3--
tensor([[[[8.1735e-39, 5.9694e-39, 8.9082e-39],
          [1.0194e-38, 9.1837e-39, 4.6837e-39]],

         [[9.9184e-39, 9.0000e-39, 1.0561e-38],
          [1.0653e-38, 4.1327e-39, 8.9082e-39]]],


        [[[9.8265e-39, 9.4592e-39, 1.0561e-38],
          [1.0010e-38, 1.0653e-38, 9.9184e-39]],

         [[1.0653e-38, 9.6429e-39, 8.4490e-39],
     

In [3]:
# random tensors, zeros y ones
rand_x = torch.rand(2,2)
print("RANDOM")
print(rand_x)
zero_x = torch.zeros(2,2)
print("ZEROS")
print(zero_x)
one_x = torch.ones(2,3)
print("ONES")
print(one_x)

RANDOM
tensor([[0.3221, 0.2166],
        [0.6320, 0.9715]])
ZEROS
tensor([[0., 0.],
        [0., 0.]])
ONES
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
# especificar tipo de dato
x = torch.rand(2,2)
print("NO ESPECIFICADO")
print(x.dtype)
x = torch.rand(2,2, dtype=torch.float16) #double,float16,int, etc...
print("ESPECIFICAO")
print(x.dtype)

NO ESPECIFICADO
torch.float32
ESPECIFICAO
torch.float16


In [5]:
# size
x = torch.rand(2,2)
print(x.size())

torch.Size([2, 2])


In [6]:
# constuir tensor desde lista
lista=[2.5,0.1]
x = torch.tensor(lista)
print(x)

tensor([2.5000, 0.1000])


In [7]:
# operaciones
x = torch.tensor([[1,1],[2,2]])
y = torch.tensor([[3,3],[4,4]])
print(x)
print(y)
print("SUMA (wise addition)")
z = x + y
print(z)
print("tambien se puede sumar de estas maneras")
z = torch.add(x,y)
print(z)
y.add_(x)
print(y)




tensor([[1, 1],
        [2, 2]])
tensor([[3, 3],
        [4, 4]])
SUMA (wise addition)
tensor([[4, 4],
        [6, 6]])
tambien se puede sumar de estas maneras
tensor([[4, 4],
        [6, 6]])
tensor([[4, 4],
        [6, 6]])


In [8]:
print("lo mismo para otras operaciones")
print("resta")
x = torch.tensor([[1,1],[2,2]])
y = torch.tensor([[3,3],[4,4]])
z = x - y
print(z)
z = torch.sub(x,y)
print(z)

print("multiplicacion")
x = torch.tensor([[1,1],[2,2]])
y = torch.tensor([[3,3],[4,4]])
z = x * y
print(z)
z = torch.mul(x,y)
print(z)

print("division")
x = torch.tensor([[1,1],[2,2]])
y = torch.tensor([[3,3],[4,4]])
z = x / y
print(z)
z = torch.div(x,y)
print(z)

lo mismo para otras operaciones
resta
tensor([[-2, -2],
        [-2, -2]])
tensor([[-2, -2],
        [-2, -2]])
multiplicacion
tensor([[3, 3],
        [8, 8]])
tensor([[3, 3],
        [8, 8]])
division
tensor([[0.3333, 0.3333],
        [0.5000, 0.5000]])
tensor([[0.3333, 0.3333],
        [0.5000, 0.5000]])


In [9]:
print("al igual q en las listas o en los array podemos tomar cierta cantidad de arreglos")
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,1])
print(x[1,:])
print(x[1,1].item()) #solo valor

print("por supuesto el reshape aqui llamado view, q es improtante")
y = x.view(15)
a = torch.tensor([[1,1],[2,2]])
b = a.view(4)


print(y)
print(b)
print("...................")
print("otro ejemplo")
j = torch.rand(4,4)
print(j)
k = j.view(16)
print(k)
print(k.size())
k = j.view(-1, 8) # Especificar otro reshape
print(k)
print(k.size())

al igual q en las listas o en los array podemos tomar cierta cantidad de arreglos
tensor([[1.6340e-01, 2.3948e-02, 2.1202e-01],
        [8.7774e-01, 3.5861e-01, 1.5219e-01],
        [6.8710e-01, 1.4552e-01, 4.6609e-01],
        [3.7665e-01, 9.2345e-01, 9.5619e-02],
        [7.5889e-04, 5.9655e-01, 8.7550e-01]])
tensor([1.6340e-01, 8.7774e-01, 6.8710e-01, 3.7665e-01, 7.5889e-04])
tensor(0.3586)
tensor([0.8777, 0.3586, 0.1522])
0.3586078882217407
por supuesto el reshape aqui llamado view, q es improtante
tensor([1.6340e-01, 2.3948e-02, 2.1202e-01, 8.7774e-01, 3.5861e-01, 1.5219e-01,
        6.8710e-01, 1.4552e-01, 4.6609e-01, 3.7665e-01, 9.2345e-01, 9.5619e-02,
        7.5889e-04, 5.9655e-01, 8.7550e-01])
tensor([1, 1, 2, 2])
...................
otro ejemplo
tensor([[0.8492, 0.7535, 0.9794, 0.1725],
        [0.1704, 0.3784, 0.9173, 0.9872],
        [0.3129, 0.8009, 0.1578, 0.9679],
        [0.6900, 0.7574, 0.0841, 0.4286]])
tensor([0.8492, 0.7535, 0.9794, 0.1725, 0.1704, 0.3784, 0.9173, 

In [18]:
print("combinando con numpy")
print("1 - convertir a numpy")
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(a))
print(type(b))

print("2 - observe que el array creado tiene como referencia el primer tensor, entonces si operamos sobre el tensor, tambien se aplica al array")
a.add_(1)
print(a)
print(b)

print("3 - pasar de numpy a torch tensor, si opero sobre el array podria pasar lo mismo de arriba")
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
print("si al operar en un array tambn cambia el tensor es xq CUDA esta habilitado (o alreves), esto es xq el tensor y sus operaciones estan haciendose en la GPU")
a = a + 1
print(a)
print(b)
print("checkeando CUDA")
print(torch.cuda.is_available())



combinando con numpy
1 - convertir a numpy
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
2 - observe que el array creado tiene como referencia el primer tensor, entonces si operamos sobre el tensor, tambien se aplica al array
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
3 - pasar de numpy a torch tensor, si opero sobre el array pasa lo mismo
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
esto sucede porque el tensor esta en el GPU, y se puede desabilitar con CUDA
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
False


In [19]:
print("especificar el device de CUDA para crear tensor en la GPU, SOLO SI CUDA ESTA DISPONIBLE") 
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = toch.ones(5, device=device) #Crear un tensor en la GPU
    #o mover a GPU
    y = torch.ones(5)
    y.to(device)
    z = x+y
    # LAS OPERACIONES REALIZADAS EN GPU SON MAS RAPIDASPERO...
    ## SI OPERO CON NUMPY ENTREGARA ERROR, PUES...
    #¡¡NUMPY SOLO PUEDE MANEJAR TENSORES EN CPU!!"
    # https://youtu.be/c36lUUr864M?list=RDCMUCbXgNpp0jedKWcQiULLbDTA&t=1440
    
    z = z.to("cpu") # mover  CPU

especificar el device de CUDA para crear tensor en la GPU, SOLO SI CUDA ESTA DISPONIBLE


In [25]:
print("a veces los tensores  requieren el argumento grad")
x = torch.ones(5, requires_grad=True)
print(x)

print("esto le dice a pytorch que mas adelante necesitare calcular los gradientes de este tensor, lo que permite mayor optimizacion a la larga ")
print("en general se usa harto (OJO, SI SE DEJA POR DEFECTO ENTONCES SERA FALSO)")

a veces los tensores  requieren el argumento grad
tensor([1., 1., 1., 1., 1.], requires_grad=True)
esto le dice a pytorch que mas adelante necesitare calcular los gradientes de este tensor, lo que permite mayor optimizacion a la larga 
en general se usa harto (OJO, SI SE DEJA POR DEFECTO ENTONCES SERA FALSO)
